### ISSUE TITLE
Обращение ajax-ом к :user_omniauth_callback_path провоцирует ошибку invalid_credentials

### ISSUE THREAD

**Issue by adolgoff** [mamantoha/omniauth-vkontakte#23]
Лог ошибки:
(vkontakte) Callback phase initiated.
(vkontakte) Authentication failure! invalid_credentials: OAuth2::Error, invalid_grant: Code is invalid or expired.
{"error":"invalid_grant","error_description":"Code is invalid or expired."}

Точно такая же ошибка была с omniauth-facebook 1.4.1, но если откатить до 1.4.0 все работает отлично:
(facebook) Callback phase initiated.
Started GET "/users/auth/facebook/callback" for 127.0.0.1 at 2013-04-18 18:33:56 +0400
Processing by Users::OmniauthCallbacksController#facebook as _/_
  User Load (142.3ms)  SELECT "users".\* FROM "users" WHERE "users"."url" = 'http://www.facebook.com/...' LIMIT 1

Я пока сам не нашел в чем решающая разница между 1.4.1 и 1.4.0

**Comment by glafir** [comment]
А как вы отследили ошибку? У меня без аякса

Started GET "/users/auth/vkontakte/callback?locale=ru&code=382b2d8adb70c9ac2e&state=ec5b045ec05cc29ad27
e07317514667ff81a94eb7ded5f14" for 185.34.180.169 at 2015-10-22 00:02:53 +0300
Processing by Users::OmniauthCallbacksController#failure as HTML
  Parameters: {"locale"=>"ru", "code"=>"382b2d8adb70c9ac2e", "state"=>"ec5b045ec05cc29ad27e07317514667f
f81a94eb7ded5f14"}
Redirected to http://bagche.ru/users/sign_in?locale=ru
Completed 302 Found in 2ms (ActiveRecord: 0.0ms)

И выкидывает с ошибкой  "Invalid credentials".
