### ISSUE TITLE
Работает ли данный модуль со Standalone приложениями?

### ISSUE THREAD

**Issue by cmrd-senya** [mamantoha/omniauth-vkontakte#39]
При авторизации он хочет сделать редирект на URI. В VK у меня создано Standalone приложение, а работать пытаюсь с локально развернутого веб приложения, у которого URI это http://192.168.56.101:3000. Соответственно VK выдает мне
> {"error":"invalid_request","error_description":"redirect_uri is incorrect, check application domain in the settings page"}

Могу ли я авторизоваться к локальному веб приложению? И как мне его тогда регистрировать в VK, как Standalone или как веб-сайт?

**Comment by mamantoha** [comment]
Выберите тип "Веб-сайт"; В качестве адреса сайта введите что-то типа `http://example.com`. Базовый домен: `example.com`.

И прописать - `127.0.0.1 example.com` или `localhost example.com`, в файле `/windows/system32/hosts` (для Windows) или `/etc/hosts` (для Linux).

На 80 порту должно работать.

**Comment by cmrd-senya** [comment]
Работает!

Дуже дякую.
