### ISSUE TITLE
redirect_uri is invalid, please pass same redirect_uri, you used in authorize method

### ISSUE THREAD

**Issue by Stajor** [mamantoha/omniauth-vkontakte#43]
I can't make login via Devise
config.omniauth :vkontakte, 'APP_ID', 'APP_SECRET', scope: 'friends,audio,email,offline,video'
url: localhost:3000/users/auth/vkontakte
And I get an error

```
I, [2015-11-04T13:32:16.541188 #13163]  INFO -- omniauth: (vkontakte) Callback phase initiated.
E, [2015-11-04T13:32:17.002804 #13163] ERROR -- omniauth: (vkontakte) Authentication failure! invalid_credentials: OAuth2::Error, invalid_grant: redirect_uri is invalid, please pass same redirect_uri, you used in authorize method.
{"error":"invalid_grant","error_description":"redirect_uri is invalid, please pass same redirect_uri, you used in authorize method."}
Processing by OmniauthCallbacksController#failure as HTML
```

**Comment by thorn** [comment]
Got the same error too so rolled back to 1.3.3 version of gem.

**Comment by mamantoha** [comment]
I will take a look at the problemit this weekend.

**Comment by mamantoha** [comment]
It was not difficult: https://github.com/mamantoha/omniauth-vkontakte/commit/7c400fcf5b98f9b22bb5abd40a4f4a2d1f6f7808

Fix released in 1.3.6.
@thorn @Stajor please test this and  let me know if there is anything else.

**Comment by Stajor** [comment]
working
thanks
:+1:

**Comment by thorn** [comment]
+1
Confirmed, thank you!
