### ISSUE TITLE
Работа с development

### ISSUE THREAD

**Issue by asiniy** [mamantoha/omniauth-vkontakte#5]
Создал приложение, в Gemfile: gem 'omniauth-vkontakte'.

Настроил omniauth.rb, в настройке приложения на сайте вк указал: 
адрес сайта: http://localhost:3000/
базовый домен: localhost

Всё бы ничего, но когда я делаю link_to "регистрируйтесь вк", "/auth/vkontakte", мне вылезает вот это:

{"error":"invalid_request","error_description":"redirect_uri has wrong domain, check application settings"}

Строка логина:
https://oauth.vk.com/authorize?response_type=code&client_id=***&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fvkontakte%2Fcallback

А для facebook и twitter всё работает. В чём дело?

**Comment by stimoshik** [comment]
You can use in your /etc/hosts:

127.0.0.1 myserver.com
