### ISSUE TITLE
Работа в develompent

### ISSUE THREAD

**Issue by Seybo** [mamantoha/omniauth-vkontakte#56]
Привет. 

Я новичок и мне достался проект с твоим гемом. Разработчик предыдущий вел разработку прямо с продакшен-сервера и поэтому, видимо, не сталкивался с той проблемой, с которой столкнулся я, и ничем помочь мне не может. А проблема у меня такая же, как и вот [в этой ветке](https://github.com/mamantoha/omniauth-vkontakte/issues/5), но у меня не получается ее решить тем способом, который там указан. 

Т.е. мой продакшен работает по адресу, скажем, xyz.ru
Я иду в `/etc/hosts`, комментирую `# 127.0.0.1	localhost` и добавляю `127.0.0.1 xyz.ru`
Все верно? 
После этого перезагружаю систему, делаю rails s и получаю 
`.rbenv/versions/2.2.2/lib/ruby/2.2.0/socket.rb:232:in 'getaddrinfo': getaddrinfo: Name or service not known (SocketError)`

Убиваю процесс и запускаю сервер заново. Он запускается.
`=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000`

Но при этом в ответ на `/auth/vkontakte`, мне снова вылезает вот это:
`{"error":"invalid_request","error_description":"redirect_uri has wrong domain, check application settings"}` и запрос снова содержит `redirect_uri=http%3A%2F%2Flocalhost%3A3000`

Там было написано еще запустить сервер на 80-м порту, но я не могу это сделать, тк в ответ на `rails s -p 80` получаю `Permission denied - bind(2) for 127.0.0.1:80 (Errno::EACCES)`

Буду очень благодарен за помощь, самостоятельно разобраться не получается. Готов предоставить любую неоходимую информацию.

**Comment by mamantoha** [comment]
Привет.

Да, сервер надо запускать на 80 порту и использовать host как в настройках приложения. Я для этих целей в development использую puma-dev или pow(для macOS). Так же можно запускать rails на 80 порту через sudo(не рекомендую так делать)

**Comment by Seybo** [comment]
ок. Решил для начала попробовать через sudo. Установил его для rbenv, выставил нужную связь в hosts и запускаю: `rbenv sudo rails s -p 80`

> [sudo] password for user: 
> => Booting WEBrick
> => Rails 4.2.1 application starting in development on http://localhost:80
> => Run `rails server -h` for more startup options
> => Ctrl-C to shutdown server
> [2016-12-08 15:00:44] INFO  WEBrick 1.3.1
> [2016-12-08 15:00:44] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
> Exiting
> /home/user/.rbenv/versions/2.2.2/lib/ruby/2.2.0/socket.rb:232:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
> 

я что-то делаю не так?

сразу же запускаю снова и тогда сервер запускается:
> rbenv sudo rails s -p 80
> => Booting WEBrick
> => Rails 4.2.1 application starting in development on http://localhost:80
> => Run `rails server -h` for more startup options
> => Ctrl-C to shutdown server
> [2016-12-08 15:01:14] INFO  WEBrick 1.3.1
> [2016-12-08 15:01:14] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
> [2016-12-08 15:01:15] INFO  WEBrick::HTTPServer#start: pid=4194 port=80

захожу на localhost, все работает, пытаюсь обратиться к `/auth/vkontakte`

и получаю ту же ошибку `{"error":"invalid_request","error_description":"redirect_uri has wrong domain, check application settings"}` и вижу, что в запросе снова `&redirect_uri=http%3A%2F%2Flocalhost%`

**Comment by mamantoha** [comment]
Попробуй заходить не на `localhost`, а на `xyz.ru`. Так же проверь не занят ли 80 порт. Возможно у тебя там висит Apache

**Comment by Seybo** [comment]
обратиться по `xyz` не удается, выдает `This site can’t be reached`
а на 80-ом порту у меня висит вот что

> sudo lsof -i tcp:80
> COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> plugin_ho 4359 glaux   20u  IPv4  28468      0t0  TCP 192.168.0.100:39474->209-20-75-76.slicehost.net:http (CLOSE_WAIT)
> chrome    4905 glaux  127u  IPv4  47619      0t0  TCP 192.168.0.100:54414->sc-in-f114.1e100.net:http (ESTABLISHED)
> ruby      5470  root   10u  IPv6  51612      0t0  TCP ip6-localhost:http (LISTEN)
> ruby      5470  root   11u  IPv4  51613      0t0  TCP xyz.ru:http (LISTEN)

убить эти процессы не удается почему-то

**Comment by mamantoha** [comment]
`127.0.0.1 xyz.ru` точно прописан в `/etc/hosts`?

**Comment by Seybo** [comment]
ок, разобрался. Видимо проблема была в кеше хрома, тк в другом браузере все заработало. Спасибо за помощь! :)

А почему лучше использовать puma-dev?

**Comment by mamantoha** [comment]
Мне так удобней, когда много разных проектов.
