### ISSUE TITLE
Offline Access

### ISSUE THREAD

**Issue by magicalbanana** [mamantoha/omniauth-vkontakte#57]
Adding `{ scope: 'offline' }` doesn't seem to work when requesting tokens that don't expire. I still get an expiration time and true for expires.

```
"credentials"=>{"token"=>"some_token", "expires_at"=>1482941649, "expires"=>true},
```

And when I do authorize I see that it's asking for offline access but seems to have an expiration still.

**Comment by merqlove** [comment]
Sure, i see here no logic about current pattern. PR is welcome 👍

**Comment by magicalbanana** [comment]
Where do I start? Sorry, not familiar with this lib.

**Comment by merqlove** [comment]
@magicalbanana look here:
- https://github.com/zquestz/omniauth-google-oauth2/search?utf8=✓&q=offline
Example Implementation

Code parts:
- https://github.com/mamantoha/omniauth-vkontakte/blob/master/lib/omniauth/strategies/vkontakte.rb#L80

**Comment by magicalbanana** [comment]
You know thing is when I do authorize an app with VK I do see the request for offline access but it still returns an `expires_at` and `expires`.

**Comment by merqlove** [comment]
Yep, seems that it's bug of VK.api version, which is supported by current gem. 
Manual said:
```
offline 
(+65536)	Access to API at any time (you will receive expires_in = 0 in this case).
```

**Comment by magicalbanana** [comment]
Yeah, so how do I fix this? If there's any.

**Comment by magicalbanana** [comment]
![image](https://cloud.githubusercontent.com/assets/7953984/21556169/010fd386-cde4-11e6-85ff-07782b8e9f6b.png)

Here's a sample, it is asking me for offline access but like I said the fields denoting expiry of the token don't return what it's supposed to return.

**Comment by merqlove** [comment]
Try to debug it, by log' and/or debugger. You will see the true picture. You have to determine where is the `method` or option within Intridea Oauth2, which is responsive for expiration.

- https://github.com/intridea/oauth2/blob/bddb74857064749184942e2727f35d0d2ea2a534/lib/oauth2/access_token.rb#L40

**Comment by magicalbanana** [comment]
I think I got it, the attribute that returns it is `expires_in` not `expires_at` as mentioned in the dev guide.
