### ISSUE TITLE
иногда выскакивает NoRawData

### ISSUE THREAD

**Issue by danielmyasnikov** [mamantoha/omniauth-vkontakte#79]
использую:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :vkontakte, ENV['API_ID'], ENV['API_SECRET'],
           scope: 'friends',
           lang: 'ru',
           https: 1,
           image_size: 'original'
end
```

Работает безупречно во всех случаев кроме нескольких профайлов. Интересно что другие интеграции с LinkedIn например выдают `{}` что бы пользователь продолжил регистрацию.

Могли бы объяснить почему решили остановить пользователя от дальнейшей регистрации с помощью метода `fail!`

И вообще в каких случаях может Контакт возвращать пустой ответ?

**Comment by Kein1945** [comment]
У нас на продакшне начало выходить постоянно, проблема в версии API который запрашивается у VK. Я обновил версию, можно пока использовать мой форк:
gem 'omniauth-vkontakte', git: 'https://github.com/Kein1945/omniauth-vkontakte'
Как будет принят пулл реквест, все будет работать нормально: https://github.com/mamantoha/omniauth-vkontakte/pull/80

**Comment by mamantoha** [comment]
Спасибо @Kein1945 :pray:  . Обновил версию на Rubygems.
