### ISSUE TITLE
Creating a gem release for omniauth-oauth2 dependency update

### ISSUE THREAD

**Issue by davidtaylorhq** [mamantoha/omniauth-vkontakte#86]
Hi @mamantoha - at @discourse we use this gem for our https://github.com/discourse/discourse-vk-auth plugin. Thanks for all your work on maintaining it!

Discourse has recently updated to `omniauth-oauth2` `v1.7.2`, which is listed as incompatible with `omniauth-vkontakte` `1.7.0`. I see that https://github.com/mamantoha/omniauth-vkontakte/commit/45fd03e6c321f53dd4dc5b7950c9a8a8490e7021 fixed this problem. Would it be possible to bump the version to `1.7.1` and release it?

**Comment by mamantoha** [comment]
Hi @davidtaylorhq . Sure. Done - https://rubygems.org/gems/omniauth-vkontakte/versions/1.7.1

**Comment by davidtaylorhq** [comment]
Wow, thanks so much for the super-fast response! 🚀
