### ISSUE TITLE
{"error":"invalid_client","error_description":"client_id is undefined"}

### ISSUE THREAD

**Issue by ananevam** [mamantoha/omniauth-vkontakte#89]
В геме oauth2 поменялась auth_scheme по умолчанию с request_body на basic_auth.
Если у вас возникает ошибка client_id is undefined, нужно добавить настройку client_options - auth_scheme
```
config.omniauth :vkontakte,
  ENV['VK_API_ID'], ENV['VK_API_SECRET'],
  client_options: {
    auth_scheme: 'request_body'
  }
```
Такая же проблема в геме omniauth-apple - https://github.com/nhosoya/omniauth-apple/issues/85

**Comment by mamantoha** [comment]
@ananevam fixed.

Или обновить `omniauth-vkontakte` до последней версии 1.8.1
